version: '3.5'

services:
  customermanagementapi:
    image: customermanagementapi
    ports: 
      - "4002:5000"
    build:
      context: .
      dockerfile: CustomerManagementAPI/Dockerfile
    networks:
      - blackyellow

  mongo:
    image: mongo:3.4
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - db_mongo:/data/db
    networks:
      - blackyellow

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    networks:
     - blackyellow
    ports:
      - "15672:15672"
      - "5672:5672"

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - blackyellow
    # network_mode: host
    volumes: 
      - redis:/data

volumes:
  db_mongo:
    driver: local
  rabbitmqdata:
    driver: local
  redis:
    driver: local

networks: 
  blackyellow: 
    name: blackyellow
