version: '3'

services:
  customermanagementapi:
    image: customermanagementapi
    ports: 
      - "4002:5000"
    build:
      context: .
      dockerfile: CustomerManagementAPI/Dockerfile

    networks:
      - customermanagementapi

# Inicio da configuracao do MongoDB
  blackyellow_db:
    image: mongo:3.4
    ports:
      - "27017"
    volumes:
      - db_mongo:/data/db
    networks:
      - customermanagementapi
    restart: always
    command: --storageEngine wiredTiger
    environment: 
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: GPX4WOwpcvOc9Wm70gAG8It7tKA0Cy090ZVO82cEJsExogsMDY
# Fim da configuracao do MongoDB

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmquser
      - RABBITMQ_DEFAULT_PASS=DEBmbwkSrzy9D1T9cJfa

volumes:
  db_mongo:
  rabbitmqdata:
    external: true
networks: 
  customermanagementapi: 
    driver: bridge
