FROM  microsoft/aspnetcore-build:2.0 AS base
WORKDIR /app
EXPOSE 5000

FROM  microsoft/aspnetcore-build:2.0 AS build
WORKDIR /src
COPY *.sln ./
COPY CustomerManagementAPI/CustomerManagementAPI.csproj CustomerManagementAPI/
RUN dotnet restore
COPY . .
WORKDIR /src/CustomerManagementAPI
RUN dotnet build -c Release -o /app

FROM build AS publish
RUN dotnet publish -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "CustomerManagementAPI.dll"]
